if(NOT DEFINED INPUT_DIRS AND NOT DEFINED INPUT_DIR)
    message(FATAL_ERROR "INPUT_DIRS or INPUT_DIR is required")
endif()
if(NOT DEFINED OUTPUT_CPP)
    message(FATAL_ERROR "OUTPUT_CPP is required")
endif()

if(DEFINED INPUT_DIRS)
    set(INPUT_DIR_LIST ${INPUT_DIRS})
else()
    set(INPUT_DIR_LIST ${INPUT_DIR})
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT_CPP}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(CPP_CONTENT "// Generated by GenerateEmbeddedAssets.cmake. Do not edit.\n")
string(APPEND CPP_CONTENT "#include \"EmbeddedAssets.h\"\n")
string(APPEND CPP_CONTENT "\n#include <cstddef>\n#include <optional>\n#include <string_view>\n\n")
string(APPEND CPP_CONTENT "namespace openchordix::assets\n{\n")

set(ENTRY_LINES "")
set(ASSET_NAMES "")

foreach(INPUT_DIR IN LISTS INPUT_DIR_LIST)
    if(NOT IS_DIRECTORY "${INPUT_DIR}")
        message(FATAL_ERROR "INPUT_DIR does not exist: ${INPUT_DIR}")
    endif()

    file(GLOB_RECURSE ASSET_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
    list(SORT ASSET_FILES)

    foreach(ASSET IN LISTS ASSET_FILES)
        set(SRC_PATH "${INPUT_DIR}/${ASSET}")
        if(IS_DIRECTORY "${SRC_PATH}")
            continue()
        endif()

        string(REPLACE "\\" "/" ASSET "${ASSET}")
        list(FIND ASSET_NAMES "${ASSET}" ASSET_INDEX)
        if(NOT ASSET_INDEX EQUAL -1)
            message(FATAL_ERROR "Duplicate embedded asset path: ${ASSET}")
        endif()
        list(APPEND ASSET_NAMES "${ASSET}")

        string(REGEX REPLACE "[^A-Za-z0-9_]" "_" SYMBOL_NAME "${ASSET}")
        set(SYMBOL_NAME "asset_${SYMBOL_NAME}")

        file(READ "${SRC_PATH}" HEXDATA HEX)
        string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," BYTE_LIST "${HEXDATA}")

        string(APPEND CPP_CONTENT "static const unsigned char ${SYMBOL_NAME}[] = {${BYTE_LIST}};\n")
        list(APPEND ENTRY_LINES "    {${SYMBOL_NAME}, sizeof(${SYMBOL_NAME}), \"${ASSET}\"}")
    endforeach()
endforeach()

string(APPEND CPP_CONTENT "static const EmbeddedAssetView kEmbeddedAssets[] = {\n")
if(ENTRY_LINES)
    string(JOIN ",\n" ENTRIES ${ENTRY_LINES})
    string(APPEND CPP_CONTENT "${ENTRIES}\n")
endif()
string(APPEND CPP_CONTENT "};\n\n")

string(APPEND CPP_CONTENT "std::optional<EmbeddedAssetView> findEmbeddedAsset(std::string_view name)\n{\n")
string(APPEND CPP_CONTENT "    for (const auto &entry : kEmbeddedAssets)\n    {\n        if (name == entry.name)\n        {\n            return EmbeddedAssetView{entry.data, entry.size, entry.name};\n        }\n    }\n    return std::nullopt;\n}\n")
string(APPEND CPP_CONTENT "\nstd::span<const EmbeddedAssetView> listEmbeddedAssets()\n{\n")
string(APPEND CPP_CONTENT "    return std::span<const EmbeddedAssetView>(kEmbeddedAssets, sizeof(kEmbeddedAssets) / sizeof(kEmbeddedAssets[0]));\n}\n")
string(APPEND CPP_CONTENT "}\n")

file(WRITE "${OUTPUT_CPP}" "${CPP_CONTENT}")
